# Cross match LEGACY and Lyttle 2021

In [3]:
import os
import pandas as pd

from astropy.io import ascii

In [5]:
data_dir = 'data'

legacy_table = ascii.read(os.path.join(data_dir, 'LEGACY/globals.dat'))
lyttle_table = ascii.read(os.path.join(data_dir, 'Lyttle21/table1.txt'))

WARNING: UnitsWarning: 'dex' did not parse as cds unit: At col 0, Unit 'dex' not supported by the CDS SAC standard. Did you mean de? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]

In [8]:
legacy_df = legacy_table.to_pandas()
lyttle_df = lyttle_table.to_pandas()

In [9]:
legacy_df.head()

,KIC,Name,Kpmag,numax,Dnu,N,Cat,BkQ,MgQ,Teff,...,[Fe/H],e_[Fe/H],r_[Fe/H],logg,e_logg,E_logg,Vlos,e_Vlos,vsini,e_vsini
0,1435467,NaN,8.88,1407,70.4,46,F-like,5.1-17.2,NaN,6326,...,0.01,0.1,<NA>,4.100,0.009,0.009,-66.52,0.1,11.9,0.5
1,2837475,NaN,8.48,1558,75.7,54,F-like,5.1-17.2,NaN,6614,...,0.01,0.1,<NA>,4.163,0.007,0.007,-13.28,0.1,23.3,0.5
2,3427720,NaN,9.11,2737,120.1,36,Simple,5.1-17.2,NaN,6045,...,-0.06,0.1,<NA>,4.387,0.005,0.004,-22.91,0.1,2.9,0.5
3,3456181,NaN,9.66,970,52.3,45,F-like,5.1-11.3,"6, 10",6384,...,-0.15,0.1,<NA>,3.950,0.007,0.005,-50.12,0.1,8.5,0.5
4,3632418,Cassie,8.22,1167,60.7,54,F-like,5.1-17.2,NaN,6193,...,-0.12,0.1,<NA>,4.024,0.007,0.005,-19.11,0.1,8.5,0.5

In [10]:
lyttle_df.head()

,name,teff,teff_err,lum,lum_err,dnu,dnu_err,mhs,mhs_err
0,KIC10079226,5928.8413,124.836624,1.571074,0.048691,116.036,0.735,0.158945,0.074398
1,KIC10215584,5666.9160,119.333700,1.636568,0.062670,115.158,2.834,0.043014,0.068864
2,KIC10319352,5456.1690,106.654010,1.848181,0.056483,78.746,1.732,0.265175,0.064762
3,KIC10322381,6146.7905,148.578700,2.444552,0.079126,86.644,6.572,-0.316814,0.079113
4,KIC10417911,5628.2570,109.985430,3.408157,0.115068,56.138,2.099,0.335723,0.068119

In [12]:
lyttle_df['KIC'] = lyttle_df['name'].str.strip('KIC')
lyttle_df.head()

,name,teff,teff_err,lum,lum_err,dnu,dnu_err,mhs,mhs_err,KIC
0,KIC10079226,5928.8413,124.836624,1.571074,0.048691,116.036,0.735,0.158945,0.074398,10079226
1,KIC10215584,5666.9160,119.333700,1.636568,0.062670,115.158,2.834,0.043014,0.068864,10215584
2,KIC10319352,5456.1690,106.654010,1.848181,0.056483,78.746,1.732,0.265175,0.064762,10319352
3,KIC10322381,6146.7905,148.578700,2.444552,0.079126,86.644,6.572,-0.316814,0.079113,10322381
4,KIC10417911,5628.2570,109.985430,3.408157,0.115068,56.138,2.099,0.335723,0.068119,10417911

In [14]:
df = pd.merge(lyttle_df, legacy_df, on='KIC', suffixes=('_L21', '_LEG'))
df

,name,teff,teff_err,lum,lum_err,dnu,dnu_err,mhs,mhs_err,KIC,...,[Fe/H],e_[Fe/H],r_[Fe/H],logg,e_logg,E_logg,Vlos,e_Vlos,vsini,e_vsini
0,KIC10079226,5928.8413,124.836624,1.571074,0.048691,116.036,0.735,0.158945,0.074398,10079226,...,0.11,0.10,<NA>,4.366,0.005,0.005,-37.15,0.1,4.0,0.5
1,KIC10963065,6039.7820,139.102700,1.883539,0.060192,103.211,0.108,-0.163979,0.076755,10963065,...,-0.19,0.10,<NA>,4.277,0.011,0.011,-54.95,0.1,4.5,0.5
2,KIC3427720,5992.9775,131.756900,1.486084,0.046410,120.045,0.120,0.008969,0.075779,3427720,...,-0.06,0.10,<NA>,4.387,0.005,0.004,-22.91,0.1,2.9,0.5
3,KIC3656476,5583.0280,109.906480,1.527948,0.047990,93.305,0.079,0.286964,0.067221,3656476,...,0.25,0.10,<NA>,4.225,0.008,0.010,-13.29,0.1,2.3,0.5
4,KIC3735871,5960.3850,131.760040,1.366482,0.043845,122.856,0.472,-0.029106,0.075043,3735871,...,-0.04,0.10,<NA>,4.396,0.007,0.007,6.90,0.1,4.8,0.5
5,KIC5950854,5914.0347,134.600000,1.813844,0.062565,96.857,0.194,-0.173085,0.073964,5950854,...,-0.23,0.10,<NA>,4.238,0.007,0.007,-42.49,0.1,3.0,0.5
6,KIC6116048,6003.9927,138.767490,1.835281,0.057154,100.891,0.089,-0.195935,0.075934,6116048,...,-0.23,0.10,<NA>,4.254,0.009,0.012,-53.26,0.1,4.0,0.5
7,KIC6603624,5424.1636,105.603935,1.083864,0.037821,110.321,0.104,0.269205,0.064156,6603624,...,0.28,0.10,<NA>,4.320,0.004,0.005,-58.82,0.1,0.7,0.5
8,KIC6933899,5771.8300,123.266030,2.878510,0.101305,72.139,0.066,0.029745,0.071016,6933899,...,-0.01,0.10,<NA>,4.079,0.008,0.009,-6.97,0.1,3.6,0.5
9,KIC7106245,5874.2173,131.658110,1.479527,0.044752,111.337,0.174,-0.126710,0.073126,7106245,...,-0.99,0.19,3,4.310,0.010,0.008,NaN,NaN,NaN,NaN
10,KIC7296438,5659.3520,112.885410,1.851060,0.055703,88.743,0.110,0.264414,0.068744,7296438,...,0.19,0.10,<NA>,4.201,0.009,0.010,3.36,0.1,1.8,0.5
11,KIC7680114,5772.8145,120.695120,2.076880,0.061357,85.169,0.083,0.118596,0.071058,7680114,...,0.05,0.10,<NA>,4.172,0.008,0.010,-58.93,0.1,3.0,0.5
12,KIC8394589,6070.4785,145.535310,1.890101,0.061466,109.443,0.204,-0.319325,0.077355,8394589,...,-0.29,0.10,<NA>,4.322,0.008,0.008,22.58,0.1,6.4,0.5
13,KIC8424992,5517.5083,128.721820,0.985946,0.029900,120.914,0.305,-0.095701,0.074718,8424992,...,-0.12,0.10,<NA>,4.359,0.007,0.007,-87.63,0.1,1.3,0.5
14,KIC8938364,5765.7210,126.572420,1.815860,0.059969,85.678,0.097,-0.088233,0.070847,8938364,...,-0.13,0.10,<NA>,4.173,0.007,0.002,-68.12,0.1,2.4,0.5
15,KIC9025370,5470.0390,114.721230,1.331269,0.052619,132.707,0.429,-0.021591,0.064973,9025370,...,-0.12,0.18,2,4.423,0.007,0.004,NaN,NaN,NaN,NaN
16,KIC9098294,5858.2827,129.638080,1.439570,0.042323,109.120,0.117,-0.080366,0.072805,9098294,...,-0.18,0.10,<NA>,4.308,0.005,0.007,-71.72,0.1,3.0,0.5
17,KIC9410862,6023.2360,145.475080,1.705360,0.055464,107.552,0.160,-0.373793,0.076247,9410862,...,-0.31,0.10,<NA>,4.300,0.009,0.008,-56.84,0.1,3.8,0.5
18,KIC9955598,5344.2905,107.071590,0.597733,0.020461,153.156,0.140,0.120090,0.062651,9955598,...,0.05,0.10,<NA>,4.497,0.007,0.005,-28.48,0.1,1.1,0.5

In [16]:
df['KIC'].to_csv(os.path.join(data_dir, 'kic_ids.csv'), index=False)